name: "Release"
on:
  push:
    tags:
      - 'v*'
env:
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
  release-store-path:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
      - uses: actions/checkout@v4

      # REUSED STEP
      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          nixbuild_key: ${{ secrets.NIXBUILD_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release JSON
        run: |
          # 1. Build and verify it's cached (important for consumers!)
          nix build .#default --json | jq '.[0] | {path, narSize}' > release.json

          # 2. Ensure it exists in your binary cache so consumers can fetch it
          nix path-info --all | cachix push nix-csi

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes-file release.json \
            release.json

